# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test formation devops

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test formation devops
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: actions/checkout@v3
    
    - name: Install dep
      run: npm i
      
    - name: Install mocha
      run: npm i -g mocha
    
    - name: Run test
      run: npm run test
